### ISSUE TITLE
简化

### ISSUE THREAD

**Issue by Jack9610** [ejlchina/bean-searcher#17]
既然追求代码层面的简洁，为什么不把 mapSearcher.search(User.class, MapUtils.flat(request.getParameterMap())) 简化成mapSearcher.search(User.class)这样，不更好吗？

**Comment by ejlchina** [comment]
那检索参数呢？
因为大多数情景下都是需要参数的，所以就不增加一个无参的检索方法了。
如果确实没有参数可传，那传一个 `null` 即可：
```java
mapSearcher.search(User.class, null);
```

**Comment by troyzhxu** [comment]
在 `v4.0` 之后，已经有你建议的这个方法了：
https://bs.zhxu.cn/guide/info/versions.html#v4-0-%E7%9A%84%E6%96%B0%E7%89%B9%E6%80%A7-v4-0-2
