### ISSUE TITLE
fibonacci(n)   return n if ( 0..1 ).include? n   (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls

### ISSUE THREAD

**Issue by manjitsinghrai9** [ejlchina/bean-searcher#18]

**Comment by manjitsinghrai9** [comment]
fibonacci(n)
  return n if ( 0..1 ).include? n
  (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls

**Comment by ejlchina** [comment]
我没没明白你写的内容。
I don't understand what you written. please describe clearly.
