### ISSUE TITLE
方言设置成oracle，日期比较的sql无法转换成to_date(）

### ISSUE THREAD

**Issue by ZhouWJ0128** [ejlchina/bean-searcher#21]
条件有日期时，oracle需要转换成类似以下这种
t.create_time > to_date(?,'yyyy-mm-dd hh24:mi:ss')

目前只能
t.create_time > ?

导致出错

请问有暂时的解决方案吗？

**Comment by ejlchina** [comment]
可以在 参数过滤器里把 字符串的日期参数值 换成成 java.sql.Timestamp 或者 LocalDateTime 对象

**Comment by ejlchina** [comment]
另外，可参考：
* https://gitee.com/troyzhxu/bean-searcher/issues/I5BPLG
* https://gitee.com/troyzhxu/bean-searcher/issues/I577CU
