### ISSUE TITLE
带动态参数的子查询结果不能作为过滤条件过滤数据吗

### ISSUE THREAD

**Issue by woniujjjjjjjjjjjj** [ejlchina/bean-searcher#24]
![image](https://user-images.githubusercontent.com/99636704/153811258-c2f3df83-1453-4e41-bfcb-c0312f595275.png)
:courseId在过滤条件的时候参数没有插入进去

**Comment by ejlchina** [comment]
已在 v3.4.2 中添加新增支持，参见：https://github.com/ejlchina/bean-searcher/releases/tag/v3.4.2
