### ISSUE TITLE
希望在实体类里面,可以有排序等一些操作

### ISSUE THREAD

**Issue by ywb6583187** [ejlchina/bean-searcher#28]

**Comment by ejlchina** [comment]
已在 v3.6.0 中实现：https://github.com/ejlchina/bean-searcher/releases/tag/v3.6.0
文档： https://searcher.ejlchina.com/guide/latest/bean.html#%E9%BB%98%E8%AE%A4%E6%8E%92%E5%BA%8F%EF%BC%88since-v3-6-0%EF%BC%89
