### ISSUE TITLE
PostgreSQL使用jsonb查询，会把::jsonb变成参数

### ISSUE THREAD

**Issue by mengpp-0001** [ejlchina/bean-searcher#30]
sql字段是下面这个样子
t2.task_item_subjoin::jsonb->> 'pointName'
但我在bean里面这样定义，会给转成 t2.task_item_subjoin ?->> 'pointName'

**Comment by ejlchina** [comment]
下个版本 在参数解析是 将会忽略 连续的冒号，并添加字符转义功能。
当前版可以通过以下方法临时解决：

1、修改 Bean Searcher 的默认参数前缀，比如将它修改为 `$`：
```java
@Bean
public SnippetResolver mySnippetResolver() {
    DefaultSnippetResolver resolver = new DefaultSnippetResolver();
    resolver.setParamPrefix("$");
    return resolver;
}
```
2、重写 `DefaultSnippetResolver`，忽略连续的冒冒号：
```java
public SnippetResolver mySnippetResolver() {
    return new DefaultSnippetResolver() {
        @Override
        public SqlSnippet resolve(String fragment) {
            SqlSnippet snippet = super.resolve(fragment.replace("::", "__"));
            snippet.setSql(snippet.getSql().replace("__", "::"));
            return snippet;
        }
    };
};
}
```

**Comment by mengpp-0001** [comment]
已解决，感谢

> 下个版本 在参数解析时 将会忽略 连续的冒号，并添加字符转义功能。
> 
> 当前版本有两种临时解决方法：
> 
> ## 方法一
> 重写 ，忽略连续的冒号：`DefaultSnippetResolver`
> 
> ```java
> @Bean
> public SnippetResolver mySnippetResolver() {
>     return new DefaultSnippetResolver() {
>         @Override
>         public SqlSnippet resolve(String fragment) {
>             SqlSnippet snippet = super.resolve(fragment.replace("::", "__"));
>             snippet.setSql(snippet.getSql().replace("__", "::"));
>             return snippet;
>         }
>     };
> }
> ```
> 
> ## 方法二
> 重新定义 Bean Searcher 的嵌入参数前缀，比如将它修改为 ：`$`
> 
> ```java
> @Bean
> public SnippetResolver mySnippetResolver() {
>     DefaultSnippetResolver resolver = new DefaultSnippetResolver();
>     resolver.setParamPrefix("$");
>     return resolver;
> }
> ```
> 
> 如果项目中已经有用嵌入参数，使用这种方法需要 修改以前的实体类，要把嵌入参数的 修改为`:``$`

**Comment by ejlchina** [comment]
版本 v3.6.0 已添加转义语义：https://github.com/ejlchina/bean-searcher/releases/tag/v3.6.0
文档：https://searcher.ejlchina.com/guide/latest/bean.html#%E5%89%8D%E7%BC%80%E7%AC%A6%E8%BD%AC%E4%B9%89%EF%BC%88since-v3-6-0%EF%BC%89
