### ISSUE TITLE
当数据库是mysql时自动类型封装的问题

### ISSUE THREAD

**Issue by Rain-ziyu** [ejlchina/bean-searcher#6]
![image](https://user-images.githubusercontent.com/70049441/141239489-acccca4b-d806-4810-8735-98fa2a1753e2.png)
似乎无法正常将MySQL中的date类型转化为Java中常用的date

**Comment by ejlchina** [comment]
这需要将 实体类中的字段类型 `Date` 修改为 `LocalDateTime`, 或者添加一个 `FieldConvertor` 来转换它（如果使用 `bean-searcher-boot-starter` 依赖，声明为 Spring 的 Bean 就好）。

另：在下各版本 v3.1.0 中，将新增了 `DateFieldConvertor`,  并且 `bean-searcher-boot-starter`  将自动配置添加它。

**Comment by ejlchina** [comment]
敬请期待 ^_^
